package com.mercy.mapper.queue;

import com.mercy.model.queue.QueueUserinfo;
import com.mercy.model.queue.QueueUserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QueueUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    long countByExample(QueueUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int deleteByExample(QueueUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int insert(QueueUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int insertSelective(QueueUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    List<QueueUserinfo> selectByExample(QueueUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    QueueUserinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") QueueUserinfo record, @Param("example") QueueUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int updateByExample(@Param("record") QueueUserinfo record, @Param("example") QueueUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int updateByPrimaryKeySelective(QueueUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    int updateByPrimaryKey(QueueUserinfo record);
}