package com.mercy.mapper.queue;

import com.mercy.model.queue.QueueOrder;
import com.mercy.model.queue.QueueOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QueueOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    long countByExample(QueueOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int deleteByExample(QueueOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int insert(QueueOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int insertSelective(QueueOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    List<QueueOrder> selectByExample(QueueOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    QueueOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") QueueOrder record, @Param("example") QueueOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int updateByExample(@Param("record") QueueOrder record, @Param("example") QueueOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int updateByPrimaryKeySelective(QueueOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_order
     *
     * @mbg.generated Fri Mar 02 14:16:17 CST 2018
     */
    int updateByPrimaryKey(QueueOrder record);
}