package com.mercy.model.queue;

import java.io.Serializable;
import java.util.Date;

public class QueueUserinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.id
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.username
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.order_no
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.contact_mobile
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.sort_score
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private Integer sortScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.current_sort
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private Integer currentSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.gmt_create
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.gmt_update
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private Date gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column queue_userinfo.user_status
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.id
     *
     * @return the value of queue_userinfo.id
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.id
     *
     * @param id the value for queue_userinfo.id
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.username
     *
     * @return the value of queue_userinfo.username
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.username
     *
     * @param username the value for queue_userinfo.username
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.order_no
     *
     * @return the value of queue_userinfo.order_no
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.order_no
     *
     * @param orderNo the value for queue_userinfo.order_no
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.contact_mobile
     *
     * @return the value of queue_userinfo.contact_mobile
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.contact_mobile
     *
     * @param contactMobile the value for queue_userinfo.contact_mobile
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.sort_score
     *
     * @return the value of queue_userinfo.sort_score
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public Integer getSortScore() {
        return sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.sort_score
     *
     * @param sortScore the value for queue_userinfo.sort_score
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setSortScore(Integer sortScore) {
        this.sortScore = sortScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.current_sort
     *
     * @return the value of queue_userinfo.current_sort
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public Integer getCurrentSort() {
        return currentSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.current_sort
     *
     * @param currentSort the value for queue_userinfo.current_sort
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setCurrentSort(Integer currentSort) {
        this.currentSort = currentSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.gmt_create
     *
     * @return the value of queue_userinfo.gmt_create
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.gmt_create
     *
     * @param gmtCreate the value for queue_userinfo.gmt_create
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.gmt_update
     *
     * @return the value of queue_userinfo.gmt_update
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.gmt_update
     *
     * @param gmtUpdate the value for queue_userinfo.gmt_update
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column queue_userinfo.user_status
     *
     * @return the value of queue_userinfo.user_status
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column queue_userinfo.user_status
     *
     * @param userStatus the value for queue_userinfo.user_status
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table queue_userinfo
     *
     * @mbg.generated Mon Feb 19 12:52:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", contactMobile=").append(contactMobile);
        sb.append(", sortScore=").append(sortScore);
        sb.append(", currentSort=").append(currentSort);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", userStatus=").append(userStatus);
        sb.append("]");
        return sb.toString();
    }
}